version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.9.1

    steps:
      - checkout

      - run: npm install

      - run:
          name: truffle compile
          command: |
            sudo npm install -g truffle@4.1.3
            truffle compile

      - run: npm test


